package httpapi

import "github.com/crazy4chicken/nsc-teamusers/apidocs/go"

// DocSCIMOperations documents the bearer-protected SCIM 2.0 surface.
var DocSCIMOperations = []apidocs.Operation{
	{
		Method:      "GET",
		Path:        "/scim/v2/ServiceProviderConfig",
		Tag:         "SCIM",
		Summary:     "Read SCIM service capabilities",
		Description: "Returns supported SCIM features. PATCH add/remove/replace operations for supported user attributes and userName equality filtering are supported; full user replacement is available with PUT. Bulk and sort are not supported. The static SCIM bearer token is required.",
		Security:    "scimBearer",
		Response:    scimServiceProviderConfig{},
		ResponseExample: map[string]any{
			"schemas": []string{scimServiceProviderConfigSchema},
			"patch":   map[string]bool{"supported": true},
			"bulk":    map[string]bool{"supported": false},
			"filter":  map[string]any{"supported": true, "maxResults": 1000},
			"changePassword": map[string]bool{"supported": false},
			"sort":            map[string]bool{"supported": false},
			"etag":            map[string]bool{"supported": false},
			"authenticationSchemes": []map[string]any{{
				"type":        "oauthbearertoken",
				"name":        "SCIM Bearer Token",
				"description": "Static bearer token authentication",
				"specUri":     "https://www.rfc-editor.org/rfc/rfc6750",
				"primary":     true,
			}},
		},
		Errors: []apidocs.ErrorDoc{{Status: 401, Code: "a valid SCIM bearer token is required", Title: "Unauthorized"}},
	},
	{
		Method:      "GET",
		Path:        "/scim/v2/ResourceTypes",
		Tag:         "SCIM",
		Summary:     "List supported SCIM resource types",
		Description: "Lists User as the only supported resource type. Groups provisioning is unsupported and GET /scim/v2/Groups returns 501. The static SCIM bearer token is required.",
		Security:    "scimBearer",
		Response:    scimResourceTypesResponse{},
		ResponseExample: map[string]any{
			"schemas":      []string{scimListResponseSchema},
			"totalResults": 1,
			"startIndex":   1,
			"itemsPerPage": 1,
			"Resources": []map[string]any{{
				"schemas":  []string{scimResourceTypeSchema},
				"id":       "User",
				"name":     "User",
				"endpoint": "/Users",
				"schema":   scimUserSchema,
				"meta": map[string]string{"resourceType": "ResourceType"},
			}},
		},
		Errors: []apidocs.ErrorDoc{{Status: 401, Code: "a valid SCIM bearer token is required", Title: "Unauthorized"}},
	},
	{
		Method:      "GET",
		Path:        "/scim/v2/Users",
		Tag:         "SCIM",
		Summary:     "List SCIM users",
		Description: "Lists only externally identified users eligible for SCIM management, excluding erased users, service accounts, and users with effective IAM permissions. Uses SCIM startIndex/count pagination (startIndex is one-based; count defaults to 100 and may be zero). The only filter is userName eq \"value\"; count is capped at 1000. Invalid pagination and unsupported sort parameters return 400. Responses use application/scim+json and require the static SCIM bearer token.",
		Security:    "scimBearer",
		Response:    scimUserListResponse{},
		ResponseExample: map[string]any{
			"schemas":      []string{scimListResponseSchema},
			"totalResults": 1,
			"startIndex":   1,
			"itemsPerPage": 1,
			"Resources":   []any{map[string]any{"schemas": []string{scimUserSchema}, "id": "01J8Z3USER000000000000001", "userName": "alice", "active": true}},
		},
		Errors: []apidocs.ErrorDoc{
			{Status: 400, Code: "only a userName eq string filter is supported", Title: "Invalid Filter"},
			{Status: 401, Code: "a valid SCIM bearer token is required", Title: "Unauthorized"},
			{Status: 500, Code: "the SCIM request could not be completed", Title: "Internal Server Error"},
		},
	},
	{
		Method:      "POST",
		Path:        "/scim/v2/Users",
		Tag:         "SCIM",
		Summary:     "Create a SCIM user",
		Description: "Creates a user from userName, externalId, name/displayName, emails, and active. A non-empty externalId and userName are required. A supplied email must be a valid address and unique. A duplicate userName, externalId, or email returns 409. Include Idempotency-Key to replay a successful retry. The request and response use application/scim+json; the static SCIM bearer token is required.",
		Security:    "scimBearer",
		Request:     scimUserInput{},
		RequestExample: map[string]any{
			"schemas":    []string{scimUserSchema},
			"userName":   "alice",
			"externalId": "directory-123",
			"name":       map[string]string{"givenName": "Alice", "familyName": "Example"},
			"emails":     []map[string]any{{"value": "alice@example.test", "primary": true}},
			"active":     true,
		},
		Response: scimUserResource{},
		ResponseExample: map[string]any{
			"schemas":    []string{scimUserSchema},
			"id":         "01J8Z3USER000000000000001",
			"externalId": "directory-123",
			"userName":   "alice",
			"displayName": "Alice Example",
			"emails":     []map[string]any{{"value": "alice@example.test", "type": "work", "primary": true}},
			"active":     true,
			"meta":       map[string]any{"resourceType": "User", "created": "2026-01-01T00:00:00Z", "lastModified": "2026-01-01T00:00:00Z", "location": "/scim/v2/Users/01J8Z3USER000000000000001"},
		},
		Errors: []apidocs.ErrorDoc{
			{Status: 400, Code: "userName and externalId are required; email must be valid", Title: "Invalid Value"},
			{Status: 401, Code: "a valid SCIM bearer token is required", Title: "Unauthorized"},
			{Status: 409, Code: "userName, externalId, or email already exists", Title: "Uniqueness Conflict"},
			{Status: 415, Code: "Content-Type must be application/scim+json", Title: "Unsupported Media Type"},
			{Status: 500, Code: "the SCIM request could not be completed", Title: "Internal Server Error"},
		},
	},
	{
		Method:      "GET",
		Path:        "/scim/v2/Users/{id}",
		Tag:         "SCIM",
		Summary:     "Read a SCIM user",
		Description: "Returns one SCIM User by the service-issued id. Users without externalId, erased users, service accounts, and users with effective IAM permissions are reported as not found. The response uses application/scim+json and requires the static SCIM bearer token.",
		Security:    "scimBearer",
		Response:    scimUserResource{},
		Errors: []apidocs.ErrorDoc{
			{Status: 401, Code: "a valid SCIM bearer token is required", Title: "Unauthorized"},
			{Status: 404, Code: "the requested user was not found", Title: "Not Found"},
			{Status: 500, Code: "the SCIM request could not be completed", Title: "Internal Server Error"},
		},
	},
	{
		Method:      "PUT",
		Path:        "/scim/v2/Users/{id}",
		Tag:         "SCIM",
		Summary:     "Replace a SCIM user",
		Description: "Replaces the SCIM user's writable profile fields. userName is required; omitted displayName and emails are cleared, and active defaults to true unless explicitly false. A non-empty externalId replaces the client-owned identifier; if omitted it is preserved and it cannot be cleared. Email values must be valid and unique. Only eligible users without effective IAM permissions or service credentials may be changed; only disabled users may be activated.",
		Security:    "scimBearer",
		Request:     scimUserInput{},
		RequestExample: map[string]any{
			"userName":   "alice",
			"externalId": "directory-123",
			"emails":     []map[string]any{{"value": "alice@example.test", "type": "work", "primary": true}},
			"active":     true,
		},
		Response: scimUserResource{},
		Errors: []apidocs.ErrorDoc{
			{Status: 400, Code: "userName is required, externalId cannot be empty, or email is invalid", Title: "Invalid Value"},
			{Status: 401, Code: "a valid SCIM bearer token is required", Title: "Unauthorized"},
			{Status: 403, Code: "the SCIM target is protected or cannot be activated", Title: "Forbidden"},
			{Status: 404, Code: "the requested user was not found", Title: "Not Found"},
			{Status: 409, Code: "userName, externalId, or email already exists", Title: "Uniqueness Conflict"},
			{Status: 415, Code: "Content-Type must be application/scim+json", Title: "Unsupported Media Type"},
			{Status: 500, Code: "the SCIM request could not be completed", Title: "Internal Server Error"},
		},
	},
	{
		Method:      "PATCH",
		Path:        "/scim/v2/Users/{id}",
		Tag:         "SCIM",
		Summary:     "Update a SCIM user",
		Description: "Applies RFC 7644 add/remove/replace operations for active, name/name.formatted, displayName, and emails, including filtered paths such as emails[type eq \"work\"].value. Changed emails must be valid and unique. Only disabled users can be activated; service accounts and users with effective IAM permissions are protected. The request and response use application/scim+json; the static SCIM bearer token is required.",
		Security:    "scimBearer",
		Request:     scimPatchRequest{},
		RequestExample: map[string]any{
			"schemas": []string{scimPatchOperationSchema},
			"operations": []map[string]any{
				{"op": "replace", "path": "active", "value": false},
				{"op": "add", "path": `emails[type eq "work"].value`, "value": "alice@example.test"},
			},
		},
		Response: scimUserResource{},
		Errors: []apidocs.ErrorDoc{
			{Status: 400, Code: "the PATCH path or value is invalid, or the email address is invalid", Title: "Invalid Patch"},
			{Status: 401, Code: "a valid SCIM bearer token is required", Title: "Unauthorized"},
			{Status: 403, Code: "the SCIM target is protected or cannot be activated", Title: "Forbidden"},
			{Status: 404, Code: "the requested user was not found", Title: "Not Found"},
			{Status: 409, Code: "email is already in use", Title: "Uniqueness Conflict"},
			{Status: 415, Code: "Content-Type must be application/scim+json", Title: "Unsupported Media Type"},
			{Status: 500, Code: "the SCIM request could not be completed", Title: "Internal Server Error"},
		},
	},
	{
		Method:      "DELETE",
		Path:        "/scim/v2/Users/{id}",
		Tag:         "SCIM",
		Summary:     "Disable a SCIM user",
		Description: "Soft-deletes an eligible SCIM user by setting active to false. Erased, service-account, and effective-IAM targets are protected; the user record remains readable as disabled only while it remains eligible. Sessions are revoked, permissions invalidated, lifecycle/audit records appended, and the endpoint returns no body. The static SCIM bearer token is required.",
		Security:    "scimBearer",
		Errors: []apidocs.ErrorDoc{
			{Status: 401, Code: "a valid SCIM bearer token is required", Title: "Unauthorized"},
			{Status: 403, Code: "the SCIM target is protected", Title: "Forbidden"},
			{Status: 404, Code: "the requested user was not found", Title: "Not Found"},
			{Status: 500, Code: "the SCIM request could not be completed", Title: "Internal Server Error"},
		},
	},
	{
		Method:      "GET",
		Path:        "/scim/v2/Groups",
		Tag:         "SCIM",
		Summary:     "Report unsupported SCIM Groups",
		Description: "Groups are not provisioned by this service. ResourceTypes lists User only; this endpoint returns a SCIM 501 error. The static SCIM bearer token is required.",
		Security:    "scimBearer",
		Response:    map[string]any{},
		Errors: []apidocs.ErrorDoc{
			{Status: 401, Code: "a valid SCIM bearer token is required", Title: "Unauthorized"},
			{Status: 501, Code: "SCIM Groups provisioning is not supported", Title: "Not Implemented"},
		},
	},
}

