package httpapi

import (
	"encoding/json"
	"errors"
	"net/http"
	"strings"

	"github.com/go-chi/chi/v5/middleware"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
)

// Problem is the RFC 9457 representation returned by HTTP API failures.
type Problem struct {
	Type     string `json:"type"`
	Title    string `json:"title"`
	Status   int    `json:"status"`
	Detail   string `json:"detail,omitempty"`
	Instance string `json:"instance,omitempty"`
}

// WriteProblem writes a problem+json response. The request ID generated by
// chi's RequestID middleware is used as the problem instance.
func WriteProblem(w http.ResponseWriter, r *http.Request, status int, title, detail string) {
	instance := ""
	if r != nil {
		instance = middleware.GetReqID(r.Context())
	}
	WriteProblemInstance(w, status, title, detail, instance)
}

// WriteProblemInstance writes a problem with an explicitly supplied instance.
func WriteProblemInstance(w http.ResponseWriter, status int, title, detail, instance string) {
	if status < 400 || status > 599 {
		status = http.StatusInternalServerError
	}
	if strings.TrimSpace(title) == "" {
		title = http.StatusText(status)
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(status)
	_ = json.NewEncoder(w).Encode(Problem{
		Type:     "about:blank",
		Title:    title,
		Status:   status,
		Detail:   detail,
		Instance: instance,
	})
}

// WriteStoreProblem maps database errors to the API's stable error classes.
func WriteStoreProblem(w http.ResponseWriter, r *http.Request, err error) {
	if err == nil {
		return
	}
	if errors.Is(err, pgx.ErrNoRows) {
		WriteProblem(w, r, http.StatusNotFound, "Not Found", "the requested resource was not found")
		return
	}
	var pgErr *pgconn.PgError
	if errors.As(err, &pgErr) {
		switch pgErr.Code {
		case "23505":
			WriteProblem(w, r, http.StatusConflict, "Conflict", "the resource already exists")
			return
		case "23503":
			WriteProblem(w, r, http.StatusBadRequest, "Invalid Reference", "a referenced resource does not exist")
			return
		case "23514", "22P02":
			WriteProblem(w, r, http.StatusBadRequest, "Invalid Request", "the request contains an invalid value")
			return
		}
	}
	WriteProblem(w, r, http.StatusInternalServerError, "Internal Server Error", "the request could not be completed")
}
