package apidocs_test

import (
	"bytes"
	"os"
	"testing"

	"teamusers/internal/apidocs"
	"teamusers/internal/authn"
	"teamusers/internal/authz"
	"teamusers/internal/httpapi"
)

func TestGeneratedOpenAPIDrift(t *testing.T) {
	operations := apidocs.All(authn.DocOperations, httpapi.DocOperations, authz.DocOperations)
	apidocs.SetOperations(operations)
	operations, err := apidocs.Operations()
	if err != nil {
		t.Fatal(err)
	}
	var generated bytes.Buffer
	if err := apidocs.Emit(operations, &generated); err != nil {
		t.Fatal(err)
	}
	committed, err := os.ReadFile("../../docs/public/openapi.yaml")
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(generated.Bytes(), committed) {
		t.Fatalf("generated OpenAPI document differs from docs/public/openapi.yaml; run go run ./cmd/genspec")
	}
}
